### ISSUE TITLE
[Research] Agreement Trace Efficiency (agreement/cadaver.go)

### ISSUE THREAD

**Issue by brianolson** [algorand/go-algorand#1769] opened 2020-12-15 20:52 UTC
**Is your feature request related to a problem? Please describe.**

The agreement trace facility, known as 'cadaver' for generating traces of the agreement state machine from which to analyze hangs, can use as much as 10-20% of CPU on a busy system. Configuring it to be off `{"CadaverSizeTarget": 0}` makes things run faster but looses the debugging log.

**Describe the solution you'd like**

Improve cadaver.go to push records onto a `chan` and use a goroutine to serialize them to msgpack and write them to disk. The output Writer should be a buffered writer instead of doing a zillion 30 byte writes directly to a file.

**Comment by ian-algorand** [comment] 2020-12-21 20:09
In grooming, we determined that there would need to be some research before we commit to something like this (to determine how much of a need there is).

**Comment by algonoah** [comment] 2022-12-14 22:13
Closing as duplicate of https://github.com/algorand/go-algorand-internal/issues/2415

**Closed by algonoah** 2022-12-14 22:13 UTC
Labels: Medium Priority, Team Carbon-11
