### ISSUE TITLE
impossible to create assets with blank  f/m/r using goal.

### ISSUE THREAD

**Issue by ian-algorand** [algorand/go-algorand#574] opened 2019-12-02 18:54 UTC

**Comment by ian-algorand** [comment] 2019-12-02 18:54
Hey Shant, can you add more details to this one?

**Comment by algonautshant** [comment] 2019-12-03 19:22
goal does not allow creation of an asset without clawback, freezer, manager or reserve addresses. 

After creating the asset, freezer and clawback addresses were possible to remove.

1) When reserve address remove transaction was submitted, the address was not removed. However, no error was reported. This might be by design, but want to confirm. 

2) After the manager address is removed, the asset disappeared. 
This might be by design, but wanted to confirm.

Cases 1 and 2 are demonstrated below: 

 $ goal -d /Users/shantkarakashian/node/testnetdata/Node/ asset   config  --assetid 11825  --manager 3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI --new-reserve ""
Issued transaction from account 3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI, txid DA4Y7QU3DF37F4EGY5GELQJOFDNK7ZDXMUPSJ66ZYRZYJRW7B6FQ (fee 1000)
Transaction DA4Y7QU3DF37F4EGY5GELQJOFDNK7ZDXMUPSJ66ZYRZYJRW7B6FQ still pending as of round 3441976
Transaction DA4Y7QU3DF37F4EGY5GELQJOFDNK7ZDXMUPSJ66ZYRZYJRW7B6FQ committed in round 3441978
~/node/testnetdata/Node
 $ goal -d /Users/shantkarakashian/node/testnetdata/Node/ asset   info  --assetid 11825
Asset ID:         11825
Creator:          3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI
Asset name:       
Unit name:        
Maximum issue:    100 
Reserve amount:   100 
Issued:           0 
Default frozen:   false
Manager address:  3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI
Reserve address:  3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI
Freeze address:   
Clawback address: 

~/node/testnetdata/Node
 $ goal -d /Users/shantkarakashian/node/testnetdata/Node/ asset   config  --assetid 11825  --manager 3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI --new-manager ""
Issued transaction from account 3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI, txid HYQKTGTU3XPVCY5NDEOGUVSIDQVHF4EP6KHLNTQ65O6242LRCTPQ (fee 1000)
Transaction HYQKTGTU3XPVCY5NDEOGUVSIDQVHF4EP6KHLNTQ65O6242LRCTPQ still pending as of round 3442001
Transaction HYQKTGTU3XPVCY5NDEOGUVSIDQVHF4EP6KHLNTQ65O6242LRCTPQ committed in round 3442003
~/node/testnetdata/Node
 $ goal -d /Users/shantkarakashian/node/testnetdata/Node/ asset   info  --assetid 11825
Error processing command: HTTP 404 Not Found: failed to retrieve asset creator from the ledger
~/node/testnetdata/Node
 $ goal -d /Users/shantkarakashian/node/testnetdata/Node/ account list 
[offline]	Unnamed-0	3OF5P2KM3AWKDX3USMFUW55H3CH4RDURU4E5WZT6VWO377RX36UXEIVPDI	99993000 microAlgos	*Default

**Comment by algonautshant** [comment] 2020-05-22 05:34
The item (2) "After the manager address is removed, the asset disappeared." is no longer the case. 

The reserve address is not changed from the creator to some other address. 
goal cannot create an asset with different reserver address, however, an asset create transaction can be constructed and sent with rawsend.

**Closed** 2020-06-11 16:04 UTC
Labels: FDE
