### ISSUE TITLE
`goal account new` command does not work with relative node dir

### ISSUE THREAD

**Issue by egieseke** [algorand/go-algorand#1453] opened 2020-08-26 16:30 UTC
`goal account new` seems to expect that it is invoked from the root of the node directory.  -d . does not work.

new-host-3:Primary ericgieseke$ goal account new -d .
could not make cachedir: mkdir test/Primary/goal.cache: no such file or directory
new-host-3:Primary ericgieseke$ pwd
/Users/ericgieseke/GolandProjects/src/github.com/algorand/smart-contracts/devrel/test/Primary
new-host-3:Primary ericgieseke$ cd ../..
new-host-3:devrel ericgieseke$ goal account new -d test/Primary
Created new account with address OG5UMKN7CHIRFQ4RLR3OQYQZCWHWHNDYQ4B7YTLRQZRPGQUXE3ZVDVV5EA

**Comment by winder** [comment] 2020-09-02 14:37
Duplicate of #589

**Closed by winder** 2020-09-02 14:37 UTC
Labels: FDE, bug
