### ISSUE TITLE
Account min balance field

### ISSUE THREAD

**Issue by barnjamin** [algorand/go-algorand#2898] opened 2021-09-15 18:28 UTC
## Problem

It'd be nice to have the min balance required for an account to be computed during the API request to the algod/indexer

## Solution

Prior to sending the Account payload back to the requestor, call `MinBalance` and add it to the payload

https://github.com/algorand/go-algorand/blob/08d31fa5b3a9ace10fab9cd80b678b88d242eee7/data/basics/userBalance.go#L438

**Comment by algoanne** [comment] 2021-11-03 18:16
## Motivation 

Transactions submitted to the algod frequently fail because they would cause the min balance of an address to increase to more than the current balance of that address. 
It would be preferable for an application to know that the min balance condition will cause the transaction to fail before submitting the transaction. 

Currently, applications wanting to know an account's min balance have to calculate it themselves based on the known calculation for min balance and other information about the account. If the min balance calculation were ever to change, this would cause their implementations to break. And it's a duplication of logic. 

The min balance information can be added as part of the existing account information endpoints ([the one for algod](https://developer.algorand.org/docs/rest-apis/algod/v2/#account) and [the one for indexer](https://developer.algorand.org/docs/rest-apis/indexer/#get-v2accountsaccount-id)) since these will usually already be called before submitting the transaction and this is the natural place to put it.

**Comment by algoanne** [comment] 2021-11-03 20:12
@barnjamin if we just add this to the algod API would that work? We're wondering if there's a good reason to have it on indexer as well (if people need it they can always go to algod for it)

**Comment by algoanne** [comment] 2021-11-03 20:34
This is a duplicate of #2419, closing this issue.

**Closed by algoanne** 2021-11-03 20:34 UTC
Labels: new-feature-request, Team Scytale
