### ISSUE TITLE
DryRun: Add **opcode cost** + **running cost** Into `app-call-trace` Frames

### ISSUE THREAD

**Issue by tzaffi** [algorand/go-algorand#3714] opened 2022-03-04 00:17 UTC
## Problem: 

Currently, the total cost of a dry-run is provided under `txns.cost` (cf. [for example](https://gist.github.com/tzaffi/16f72b39faea1c3b45492caf9a7a8dfa#file-dr-json-L90)). This is very useful in the context of an execution that runs out of budget. However, there is room for improvement. Providing the explicit impact of each opcode and a running total is a nice to have, and I believe it is a fairly low hanging fruit with little downside. Yes, users could calculate this on their end, but it would be quite convenient to have this functionality available out-of-the-box.

In particular, I am proposing that each `app-call-trace` frame look something like this: 

```json
                {
                    "line": 4,
                    "pc": 13,
                    "scratch": [
                        {
                            "bytes": "ZHVtbXk=",
                            "type": 0,
                            "uint": 0
                        }
                    ],
                    "cost": {
                        "opCost": 20,
                        "runningCost": 231,
                    },
                    "stack": []
                }
```
Notice the new field `cost` with sub-fields `cost.opCost` and `cost.runningCost`

## Solution

We are already keeping the [running cumulative cost inside of our dry-run code](https://github.com/algorand/go-algorand/blob/e1ae88839dd5dba4a3900940ba8fd64d7b982f2d/daemon/algod/api/server/v2/dryrun.go#L552) so it seems fairly straight forward to add the information into our response.

## Dependencies

None

## Urgency

Medium/Low

**Comment by algoanne** [comment] 2023-01-03 21:17
duplicate of #3646

**Closed by algoanne** 2023-01-03 21:17 UTC
Labels: new-feature-request, Team Scytale
