### ISSUE TITLE
Stateless code needs block time independent "time" checking.

### ISSUE THREAD

**Issue by jannotti** [algorand/go-algorand#2352] opened 2021-06-30 16:59 UTC
Many LogicSigs would like to lock up funds for a time. Others need to "expire" (return false unconditionally) after some time.  This is complicated by the fact that stateless code must not realy on *any* state except what is in the sent transaction.

Today, LogicSigs examine their "fv" or "lv" fields, rather than as for a "current time".  They must then map a block number to the time they estimate such a block number would be added to the chain.  They do so by guessing that blocks will take ~4.5s to run, now and into the future.

With performance work that may decrease the block time, code like this needs a new strategy that is still stateless.  That is, a timestamp can't be expose to stateless code.

Strawman: Two new opcodes, `assert_before` and `assert_after`.  These opcodes examine `lv` (for `assert_before`) or `fv` (for `assert_after`) and fail the entire transaction if the transaction could take place after time T (taken from top of stack).

`assert_before` establishes a estimate for the time as of block `lv + 1`. It does this by taking the timestamp from the previous block b, and adding (lv+1-b)*(current_block_duration-safety_factor). If T exceeds that lower bound, the txn fails. safety_factor is intended to make a conservative estimate for lv+1's block time.  This is impossible in general, since block times could potentially be shortened in consensus upgrade. To be perfect, we would have to rerun logicsigs after upgrades.

`assert_after` is easier.  The check is simply that the `fv -1` block's timestamp is less than T.  If not, fail.

This all sounds more complex than one would expect.  I'd like to see something simpler that is still stateless, but I have not thought of it.

**Comment by barnjamin** [comment] 2021-06-30 17:05
Would wall clock time be something you'd expect to be provided by an external oracle?

**Comment by brianolson** [comment] 2021-06-30 21:29
There's a placeholder in the globals for block time. Block time (unix seconds since 1970-01-01 00:00:00 UTC) is probably about right. For TEAL 1, back in ~November 2019, it was initially the block time of the current block as being proposed, then we decided the committed block time of the previous block was safer, then for very cautious specific reasons it was taken out at the last minute just before release. Given the changing landscape of what we allow into LogicSig and App contexts it might be worth re-evaluating that decision?

**Comment by jannotti** [comment] 2021-06-30 23:37
I think it should actually be the block time of fv-1, otherwise we'd have to reevaluate logicsigs as the air in the transaction pool.

That's also the reasoning behind assert_after, and feels conceptually simpler. Maybe that primitive is enough : give me the unix time of my fv-1 block.

**Comment by algorandskiy** [comment] 2021-09-29 00:52
Implemented in #2789
The problem is with enabling this since it would require two consensus upgrades:
1. Store 1001 + 320 + X blocks in blockDB (needed for trackerDB rewinding)
2. Enabling `txn FirstValidTime` on a database containing all required blocks.

Decided to postpone releasing it after ledger refactoring when txTail tracker will be storing data in a database in order to eliminate the need of double upgrade.

**Comment by algorandskiy** [comment] 2022-03-25 14:37
We wait https://github.com/algorand/go-algorand/pull/3748 to be merged

**Closed** 2022-08-15 20:02 UTC
Labels: Team Scytale
